### ISSUE TITLE
Test2で特に参照するpodの翻訳をする

### ISSUE THREAD

**Issue by kfly8** [perldoc-jp/module-pod-jp#34]
## 選定背景

- Test2は、perl 5.25 から標準モジュール入りしている (Test2::Suiteは入っていないが）
- Test2は、Test::Moreと比べ、APIが扱いやすく、出力もわかりやすい、などのメリットあり
- （個人的には、Test::Deepの利用も不要になると思っている）

## TODO

- [ ] [Test2](https://metacpan.org/pod/Test2) トップの翻訳をする
- [ ] [Test2::V0](https://metacpan.org/pod/Test2%3A%3AV0)の翻訳をする
- [ ] [Test2::Tools::Compare](https://metacpan.org/pod/Test2::Tools::Compare) の翻訳をする
